### ISSUE TITLE
BasicShields-1.2.0-1.18 Fabric, Gold shield recipe not working

### ISSUE THREAD

**Issue by Zhyn-exe** [CrimsonDawn45/Basic-Shields-Fabric#26]
I think the recipe might be looking for "gold_ingots" instead of "gold_ingot"?

"Failed to parse recipe 'basicshields:golden_shield[minecraft:crafting_shaped]'! Falling back to vanilla: com.google.gson.JsonSyntaxException: Unknown item tag 'c:gold_ingots'"

**Comment by CrimsonDawn45** [comment]
It's because I was trying to make it accept the c:gold_ingots tag instead of hardcoding the item it uses. I guess I forgot to actually initialize the tag.

**Comment by CrimsonDawn45** [comment]
I'll have a bugfix update out soon

**Comment by CrimsonDawn45** [comment]
Update 1.2.1 will contain this fix

**Comment by CrimsonDawn45** [comment]
For now you can download the file from the releases tab in this github or at https://modrinth.com/mod/basic-shields-fabric. Because I'm having some issues with curseforge for some reason.
