### ISSUE TITLE
some modded enchants plainly dont work on shields

### ISSUE THREAD

**Issue by DeRp-MaSte5** [CrimsonDawn45/Basic-Shields-Fabric#30]
mods like spellbound add enchants that are compatible with shields. for example hearty. it adds hearts but you cant get it on your shields.

**Comment by CrimsonDawn45** [comment]
I'll look into it when I get the chance. There is a known issue with Fabric Shield Lib that causes a lot of problems with enchantments that shouldn't be able to be put on shields being put on them & enchantments that are only for shields not working properly.

**Comment by CrimsonDawn45** [comment]
https://www.curseforge.com/minecraft/mc-mods/spellbound-enchantments
I'm adding this link here so I can look into this more.

**Comment by CrimsonDawn45** [comment]
Fabric Shield Lib has been updated to fix this.
