### ISSUE TITLE
Add consistency in names

### ISSUE THREAD

**Issue by allethargic** [CrimsonDawn45/Basic-Shields-Fabric#31]
Quite simple request - maybe rename "Shield" to "Iron Shield".

**Comment by CrimsonDawn45** [comment]
I tried doing this already using a .lang file and it broke a lot of stuff. There may be a different way to do it that doesn't cause that Issue but right now I'm more focused on adding more integrations.

**Comment by allethargic** [comment]
Maybe release a separate Resource Pack? It allows renaming items no problem. Here is an [https://www.curseforge.com/minecraft/texture-packs/coins-resource-pack/files?__cf_chl_jschl_tk__=LD2nR6JFV8EjXFuaBHfDKRfS7MCXbrFd4d8OF3rypaE-1642721388-0-gaNycGzNDRE](example).

It'll be kinda shitty to have it as a separate thing. Is there any way to implement Resource Pack inside of a mod?

**Comment by CrimsonDawn45** [comment]
This is fixed in 1.3.0
