### ISSUE TITLE
No Cooldown on Shields exept Minecraft:Shield - 1.18.1 

### ISSUE THREAD

**Issue by SpigotDE** [CrimsonDawn45/Basic-Shields-Fabric#32]
Hey, 
i have no cooldown on your shields , i can use them at any time

Version: 1.2.1

Fabric Loader: 0.13.3
Fabric API: 0.46.4

Modpack used: The Progressor

**Comment by CrimsonDawn45** [comment]
This was an issue with Fabric Shield Lib which has been fixed.
