### ISSUE TITLE
 Game crash 

### ISSUE THREAD

**Issue by JustFoxx** [CrimsonDawn45/Basic-Shields-Fabric#33]
[latest.log](https://github.com/CrimsonDawn45/Fabric-Shield-Lib/files/8190491/latest.log)
1.18.1 fabric latest

**Comment by CrimsonDawn45** [comment]
Sorry this is because I listed some of the files as compatible with 1.18.1 when they weren't on Fabric Shield Lib. If you run Fabric Shield Lib 1.5.0 instead of 1.5.1 or 1.5.2 it should work.

**Comment by CrimsonDawn45** [comment]
Because of a bunch of big changes Mojang made in 1.18.2 The latest versions of Fabric Shield Lib for 1.18 don't support 1.18.1

**Comment by CrimsonDawn45** [comment]
The files are no longer listed as compatible with 1.18.1 so as long as you switch to 1.5.0 it should work.
