### ISSUE TITLE
Gobber Recipe Broken

### ISSUE THREAD

**Issue by Chunkey** [CrimsonDawn45/Basic-Shields-Fabric#41]
The basic gobber shield recipe is missing the gobber ingot resulting in a gobber shield from just 5 wood planks.  [See here](https://imgur.com/Cowl0EV)

Gobber2-Fabric-1.18.2-2.5.73
BasicShields-1.3.1-1.18.2
FabricShieldLib-1.5.3-1.18

**Comment by CrimsonDawn45** [comment]
I'm working on updating to 1.19 the full release for 1.19 should have this fixed.
