### ISSUE TITLE
[Bug] Mod causing other modded shields to be named "Iron Shield"

### ISSUE THREAD

**Issue by aisukuma** [CrimsonDawn45/Basic-Shields-Fabric#42]
Though it does not bother me too much about it but this mod does force some modded shield names to be called "Iron Shield" or of some other tier. Right now, I have found the issue when using [MC Dungeons Weapons](https://www.curseforge.com/minecraft/mc-mods/mcdw).

For example, this shield is from MC Dungeons Weapons **without** Basic Shields enabled:
![image](https://user-images.githubusercontent.com/22802219/169988783-eac9e70d-10e4-4b5f-beeb-262d4378f847.png)

The same shield **with** Basic Shields enabled:
![image](https://user-images.githubusercontent.com/22802219/169989694-7dff892e-15e8-43ca-a29e-51262fccd9e2.png)

Mod List
BasicShields-1.3.1-1.18.2.jar
mcdw-4.3.2.jar

**Comment by PIPILAN** [comment]
I got this problem too

**Comment by PIPILAN** [comment]
So am I

**Comment by CrimsonDawn45** [comment]
I'll look into getting this fixed by next full release

**Comment by CrimsonDawn45** [comment]
I found a fix for this bug will be in next release
