### ISSUE TITLE
Update for Minecraft 1.19

### ISSUE THREAD

**Issue by lospejos** [CrimsonDawn45/Basic-Shields-Fabric#44]
Update for Minecraft 1.19.

There are breaking changes AFAIK:
1) `new LiteralText(...)`  is now `Text.literal(...)`
2) `new TranslatableText(...)` is now `Text.translatable(...)`
3) `net.minecraft.tag.Tag` is now `net.minecraft.tag.TagKey`

**Comment by CrimsonDawn45** [comment]
Thank you for this information I'm in the process of updating to 1.19

**Comment by CrimsonDawn45** [comment]
These changes have been made the remaining work for porting to 1.19 is fixing bugs with the shield library.
