### ISSUE TITLE
Integration with Adabranium

### ISSUE THREAD

**Issue by Canters1** [CrimsonDawn45/Basic-Shields-Fabric#7]

**Comment by CrimsonDawn45** [comment]
Adabranium was one of the mods I definitely plan to add compatibility for. I just have been a bit busy lately. Next time I get the chance to work on the mod I'll probably add this in.

**Comment by CrimsonDawn45** [comment]
Ok so this is being worked on, but I'm mostly waiting on the Adabranium mod to accept my Pull Requests so I can actually import it into my workspace.

**Comment by CrimsonDawn45** [comment]
1.18:
https://github.com/Brandcraf06/Adabranium/pull/21

1.17:
https://github.com/Brandcraf06/Adabranium/pull/22

**Comment by CrimsonDawn45** [comment]
Code completely done, Now it's just time for the textures

**Comment by CrimsonDawn45** [comment]
The textures for the Adabranium shields are completely done & will be in release 1.2.0. I'm just waiting on the textures for #8
